### ISSUE TITLE
Optional PyYAML dependence?

### ISSUE THREAD

**Issue by tueda** [cheshirekow/cmake-format-precommit#1]
When one wants to use configuration files in the YAML format, `cmake-format` and `cmake-lint` require `pyyaml` (ref. [cmake-format: Configuration](https://cmake-format.readthedocs.io/en/latest/configuration.html)).

In the pre-commit framework, users can overwrite `additional_dependencies` in their `.pre-commit-config.yaml` to work with YAML configuration files:

```yaml
repos:
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.5
    hooks:
    -   id: cmake-format
        additional_dependencies: [cmake-format==0.6.5, pyyaml==5.3]
    -   id: cmake-lint
        additional_dependencies: [cmake-format==0.6.5, pyyaml==5.3]
```

but, as you see, one has to write the version number `0.6.5` 3 times in this case. This doesn't look cool.

I come up with the following 2 options to improve the above point:

1.  Always install `pyyaml` to the (isolated) pre-commit environment anyway. So, set `additional_dependencies: [cmake-format==0.6.5, pyyaml==5.3]` in [`.pre-commit-hooks.yaml`](https://github.com/cheshirekow/cmake-format-precommit/blob/ddf69c3738d64873a849e72c8dd7494dc3d94cda/.pre-commit-hooks.yaml).

2. Install `cmake-format` by the `install_requires` option of the [`setup`](https://github.com/cheshirekow/cmake-format-precommit/blob/ddf69c3738d64873a849e72c8dd7494dc3d94cda/setup.py#L2) and leave `additional_dependencies` in [`.pre-commit-hooks.yaml`](https://github.com/cheshirekow/cmake-format-precommit/blob/ddf69c3738d64873a849e72c8dd7494dc3d94cda/.pre-commit-hooks.yaml) blank by default. (See [mirrors-mypy](https://github.com/pre-commit/mirrors-mypy) as an example.) Then users can optionally add `additional_dependencies: [pyyaml==5.3]` in their `.pre-commit-config.yaml`.

**Comment by cheshirekow** [comment]
Is there no way to *append* `additional_dependencies` in your user `.pre-commit-config.yaml`? Maybe that's worth a feature request to precommit.

re: option 1:
I don't use precommit so I don't care too much, but personally I wouldn't want pyyaml coming in as a dependency by default. This package has bit me several times with API-breaking changes so I would prefer not to bring it in for users not using YAML. 

re: option 2:
I seem to recall that there was a specific reason to prefer the `additional_dependencies` option versus the `setup.py` option. I don't remember the specifics but I will dig up the original issue and see if there's a functional difference. Otherwise, this sounds like the better option to me. 

alternatively (option 3?)
This repo could provide `cmake-format-with-yaml` and `cmake-lint-with-yaml` options. 

FWIW you can install `cmake-format[YAML]==0.6.5` and skip the `pyyaml==5.3` part since cmake-format already specifies the optional dependency in it's setup.py. 

Edit: OK I can't find anything in https://github.com/cheshirekow/cmake_format/pull/44 that would preclude the dummy package option. I'll give that a try for `0.6.6` and we can see how it goes.

**Comment by tueda** [comment]
If you don't like pre-commit users hitting any problems with API-breaking changes of PyYAML in future, I think it is better to explicitly specify the PyYAML version, like `pyyaml==5.3`, in `.pre-commit-hooks.yaml` to avoid compatibility issues. Because pre-commit creates virtual environments, as far as I understand, specifying a package version leads to fixing the version of the installed package in the pre-commit framework.

**Comment by cheshirekow** [comment]
I think you misunderstood the point of my statement. The thing I don't want is that users who don't use yaml configs necessarily being forced to install the additional (potentially problematic) package. 

In any case, I switched to using `install_requires` in `setup.py`. Why don't you give tag `v0.6.6-rc1` a try and see if that works for you.

**Comment by tueda** [comment]
OK. Thank you for creating a new tag for testing.

But a syntax error happened because of a lack of "," in the end at `setup.py` line 3
https://github.com/cheshirekow/cmake-format-precommit/blob/ed6f08327051d83b62b20dad5a2bc9179f3b5b19/setup.py#L2-L6

**Comment by cheshirekow** [comment]
Got it. Can you give `v0.6.6-rc2` a try?

**Comment by tueda** [comment]
For `v0.6.6-rc2`, I got `ModuleNotFoundError: No module named 'six'`, as reporeted in   cheshirekow/cmake_format#159.

**Comment by cheshirekow** [comment]
Ok but the pre-commit stuff worked then? I'll push this tag to `v0.6.6` and close this issue.

**Comment by tueda** [comment]
OK. Yes, if I manually add `six` to the dependencies, then the tag `v0.6.6-rc2` worked (with YAML config):
```yaml
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.6-rc2
    hooks:
    - id: cmake-format
      additional_dependencies: [six==1.14.0, pyyaml==5.3]
    - id: cmake-lint
      additional_dependencies: [six==1.14.0, pyyaml==5.3]
```

Hopefully, the missing dependency on `six` will be fixed in the next version of `cmake-format`.

**Comment by tueda** [comment]
As of v0.6.9, one can use YAML configuration files with `additional_dependencies` as follows:
```yaml
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.9
    hooks:
    - id: cmake-format
      additional_dependencies: [pyyaml==5.3.1]
    - id: cmake-lint
      additional_dependencies: [pyyaml==5.3.1]
```
So, I think this issue can be closed.
